import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navigation from "@/components/navigation/navigation";
import { Footer } from "@/components/navigation/footer";
import Header from "@/components/navigation/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "الشيخ أسامة عبد العظيم",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ direction: "rtl" }}>
        <Header />
        <Navigation />
        <div className="min-h-[calc(100vh-300px)] py-7 ">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
