import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/navigation/header";
import { Footer } from "@/components/navigation/footer";
import Navigation from "@/components/navigation/navigation";
import { Locale } from "@/utils/get-dictionary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "الشيخ أسامة عبد العظيم",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const appDir = lang === "ar" ? "rtl" : "ltr";

  return (
    <html lang={lang}>
      <body className={inter.className} style={{ direction: appDir }}>
        <Header locale={lang} />
        <Navigation locale={lang} />
        <div className="min-h-[calc(100vh-300px)] py-7 ">{children}</div>
        <Footer locale={lang} />
      </body>
    </html>
  );
}
